name: Continous Deploy Demo

on:
  push:
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    shell:
      bash

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Calling Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - run: |
          workflow_file=$GITHUB_WORKSPACE/.github/workflows/cd.yml
          jobs=$(yq '.jobs[] | key' $workflow_file)
          echo $jobs


  DEV:
    runs-on: ubuntu-latest
    # environment: DEV

    steps:
      - name: deploy-to-dev
        run: echo Deploying To Dev!

  PROD:
    needs: [ DEV ]
    runs-on: ubuntu-latest
    # environment: PROD

    steps:
      - name: deploy-to-prod
        run: |
          echo '${{ toJSON(needs) }}'
          echo Deploying to PROD!
