name: Continous Deploy Demo

on:
  push:
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    shell:
      bash

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Calling Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }} # specify the triggering branch, avoids edge case bug in PR workflows

      - run: |
          workflow_file=$GITHUB_WORKSPACE/.github/workflows/cd.yml

          echo $(yq '.jobs[] | key' $workflow_file) >> $GITHUB_STEP_SUMMARY


  # DEV:
  #   runs-on: ubuntu-latest
  #   # environment: DEV

  #   steps:
  #     - name: deploy-to-dev
  #       run: echo Deploying To Dev! >> $GITHUB_STEP_SUMMARY

  # PROD:
  #   needs: [ DEV ]
  #   runs-on: ubuntu-latest
  #   # environment: PROD

  #   steps:
  #     - name: deploy-to-prod
  #       run: echo Deploying to PROD! >> $GITHUB_STEP_SUMMARY
